apiVersion: apps/v1
kind: Deployment
metadata:
  name: titanic-deployment
spec:
  selector:
    matchLabels:
      app: titanic
  template:
    metadata:
      labels:
        app: titanic
    spec:
      containers:
        - name: titanic
          image: cheloghm/titanic:v12
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          env:
            - name: MongoDbSettings__Host
              value: mongodb-service
            - name: MongodbSettings__Password
              valueFrom:
                secretKeyRef:
                  name: titanic-secrets
                  key: mongodb-password
          livenessProbe:
            httpGet:
              path: /health/live
              port: 80
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: titanic-service
spec:
  type: LoadBalancer
  selector:
    app: titanic
  ports:
    - port: 80
      targetPort: 80
